sudo: required

services:
  - docker

before_install:
  - docker build -t meliapp/1.0.1 .

script:
  - docker run meliapp/1.0.1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push meliapp/1.0.1
