version: '3'
services:
  redisdb:
    image: redis
    hostname: redis
    restart: "no"
    container_name: redisdb
    ports:
      - "6379:6379"
    environment:
      - PUID=1000
  mongodb:
    image: mongo
    hostname: mongodb
    container_name: mongodb
    restart: "no"
    ports:
      - "27017:27017"
    environment:
      PUID: 1000
      MONGO_INITDB_DATABASE: melidb
  meliapp:
    build:
      dockerfile: Dockerfile
      context: ./
    hostname: meliapp
    container_name: meliapp
    restart: "no"
    depends_on:
      mongodb:
        condition: service_started
      redisdb:
        condition: service_started
    links:
      - redisdb
      - mongodb
    ports:
      - "80:8080"
    environment:
      SPRING_DATA_MONGODB_DATABASE: melidb
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_HOST: mongodb
      SPRING_REDIS_HOST: redisdb
      SPRING_REDIS_PORT: 6379
      API_FIXER_CODE: 37ce7e9545ef3c90f4b29040c0de45a8
