version: '3'
services:
  meliapp:
    image: meli:1.0.1
    hostname: meliapp
    container_name: meliapp
    restart: "no"
    ports:
      - "8015:8080"
    environment:
      SPRING_DATA_MONGODB_DATABASE: melidb
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_HOST: mongodb
      SPRING_REDIS_HOST: redisdb
      SPRING_REDIS_PORT: 6379
      API_FIXER_CODE: 37ce7e9545ef3c90f4b29040c0de45a8






